// <auto-generated />
using System;
using EFlibassignment.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFlibassignment.Migrations
{
    [DbContext(typeof(Mycontext))]
    [Migration("20200214112549_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFlibassignment.models.Item", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("price")
                        .HasColumnType("int");

                    b.HasKey("itemId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("EFlibassignment.models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("deliverydate")
                        .HasColumnType("Date");

                    b.Property<int>("itemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("orderdate")
                        .HasColumnType("Date");

                    b.HasKey("orderId");

                    b.HasIndex("itemId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("EFlibassignment.models.Order", b =>
                {
                    b.HasOne("EFlibassignment.models.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
